//
//  Symbols.swift
//  Money
//
//  Created by Artem on 09.07.2024.
//

import Foundation

//bank.building.fill
//gauge.chart.lefthalf.righthalf

struct Symbols {
    
    static let accounts = [
        "creditcard.and.123",
        "creditcard",
        "giftcard",
        "banknote"]
    
    static let currencies = [
        "australsign",
        "australiandollarsign",
        "bahtsign",
        "bitcoinsign",
        "brazilianrealsign",
        "cedisign",
        "centsign",
        "chineseyuanrenminbisign",
        "coloncurrencysign",
        "cruzeirosign",
        "danishkronesign",
        "dongsign",
        "dollarsign",
        "eurosign",
        "eurozonesign",
        "florinsign",
        "francsign",
        "guaranisign",
        "hryvniasign",
        "indianrupeesign",
        "kipsign",
        "larisign",
        "lirasign",
        "manatsign",
        "malaysianringgitsign",
        "millsign",
        "nairasign",
        "norwegiankronesign",
        "peruviansolessign",
        "pesetasign",
        "pesosign",
        "polishzlotysign",
        "rublesign",
        "rupeesign",
        "shekelsign",
        "singaporedollarsign",
        "sterlingsign",
        "swedishkronasign",
        "tengesign",
        "tugriksign",
        "turkishlirasign",
        "yensign",
        "wonsign",
        "australsign",
        "australiandollarsign",
        "bahtsign",
        "bitcoinsign",
        "brazilianrealsign",
        "cedisign",
        "centsign",
        "chineseyuanrenminbisign",
        "coloncurrencysign",
        "cruzeirosign",
        "danishkronesign",
        "dongsign",
        "dollarsign",
        "eurosign",
        "eurozonesign",
        "florinsign",
        "francsign",
        "guaranisign",
        "hryvniasign",
        "indianrupeesign",
        "kipsign",
        "larisign",
        "lirasign",
        "manatsign",
        "malaysianringgitsign",
        "millsign",
        "nairasign",
        "norwegiankronesign",
        "peruviansolessign",
        "pesetasign",
        "pesosign",
        "polishzlotysign",
        "rublesign",
        "rupeesign",
        "shekelsign",
        "singaporedollarsign",
        "sterlingsign",
        "swedishkronasign",
        "tengesign",
        "tugriksign",
        "turkishlirasign",
        "yensign",
        "wonsign"
    ]
    
    static let objectAndTools = [
        "trash",
        "paperplane",
        "doc",
        "clipboard",
        "book",
        "book.closed",
        "magazine",
        "graduationcap",
        "dumbbell",
        "soccerball",
        "basketball",
        "tennis.racket",
        "volleyball",
        "trophy",
        "beach.umbrella",
        "gearshape",
        "scissors",
        "bag",
        "cart",
        "basket",
        "wrench.adjustable",
        "hammer",
        "wrench.and.screwdriver",
        "handbag",
        "briefcase",
        "case",
        "suitcase",
        "theatermasks",
        "powercord",
        "refrigerator",
        "tent",
        "building.2",
        "key",
        "stroller",
        "cross.vial",
        "teddybear",
        "crown",
        "tshirt",
//        "jacket",
        "shoe",
        "film",
        "comb",
        "sunglasses",
        "paintpalette",
        "cup.and.saucer",
        "wineglass",
        "birthday.cake",
        "fork.knife",
        "simcard",
        "gift"
    ]
    
    static let devices = [
        "printer",
        "scanner",
        "display",
        "pc",
        "laptopcomputer",
        "smartphone",
        "computermouse",
        "headphones",
        "earbuds",
        "av.remote",
        "tv",
        "arcade.stick.console",
        "gamecontroller",
        "camera",
        "network"]
    
    static let transportation = [
        "airplane",
        "airplane.departure",
        "car",
        "bolt.car",
        "bus",
        "tram",
        "cablecar",
        "lightrail",
        "ferry",
        "sailboat",
        "truck.box",
        "bicycle",
//        "moped",
//        "motorcycle",
        "scooter",
        "fuelpump",
        "ev.charger"]
    
    static let human = [
        "person",
        "person.2",
        "person.3",
        "figure.stand",
//        "figure.stand.dress",
        "figure.2.arms.open",
        "figure.2.and.child.holdinghands",
        "figure.and.child.holdinghands",
        "figure.2",
        "figure.run",
        "figure.american.football",
        "figure.archery",
        "figure.baseball",
        "figure.basketball",
        "figure.bowling",
        "figure.boxing",
        "figure.cricket",
        "figure.skiing.crosscountry",
        "figure.skiing.downhill",
        "figure.outdoor.cycle",
        "figure.sailing",
        "figure.strengthtraining.traditional"]
    
    static let home = [
        "house",
        "lightbulb",
        "fan",
        "lamp.desk",
        "lamp.floor",
        "lightswitch.on",
        "lightswitch.off",
        "poweroutlet.type.a",
        "poweroutlet.type.b",
        "poweroutlet.type.c",
        "spigot",
        "shower",
        "bathtub",
        "party.popper",
        "balloon",
        "frying.pan",
        "popcorn",
        "bed.double",
        "chair.lounge",
        "cabinet",
        "washer",
        "alarm",
        "hourglass"]
    
    static let nature = [
        "mountain.2",
        "hare",
        "dog",
        "tortoise",
        "cat",
        "lizard",
        "bird",
        "ant",
        "fish",
        "pawprint",
        "leaf",
        "camera.macro",
        "tree",
        "carrot"]
    
    static let health = [
//        "heart.text.clipboard",
        "heart",
        "stethoscope",
        "cross.case",
        "lungs",
        "medical.thermometer",
        "bandage",
        "syringe",
        "facemask",
        "pill",
        "pills",
        "cross"]
    
}
